#ENC[AES256_GCM,data:T/PEabMGhX0gt8YwGGO5OFSltaLTV7Z1gXKXWvpQTLyK/cji7A4E,iv:MP9G1FA4Xo+ONNkhQy+Nt6aBiioFHez1vQL/zv2//hY=,tag:/eNDrtVlM13Wdivt9K1TfA==,type:comment]
#
#ENC[AES256_GCM,data:uEh0RJ//SN7rkaM33ljuEsdv5J1FSDOnl/piQpfnxEhY0nKYkA==,iv:wDShuR5C/uoD18D36aMyupGFBdz2KCktmQSZL0TcP7c=,tag:7SQU11JRJysHHcziGHXncw==,type:comment]
#ENC[AES256_GCM,data:fKx1G1Ti9YLGMABHTRHyzJZMl20mHKoxOfvfUm2d9cNQyVw=,iv:zat7gDIlK2IcBcIs9criyttCQvuoPKfeVvSW1Ggc5Gk=,tag:1YxFkAVS48yK2UkVtZ/ZDA==,type:comment]
#
#ENC[AES256_GCM,data:wMRGbuQrUEyoNIBIqdDzSc3b+Fyt7byWpJdhTlaCEsxjHekQfsm0thZ5rOBk2OyABqZaAIiVot4ZtKdzBYyFk7pctX9LIYKFgQ==,iv:SR1hfeUvGW9IoB+9MPYuCdAuQn9YRjW3bX04iRxln8w=,tag:UQ7K0R+55kBTQet6RNfleQ==,type:comment]
#ENC[AES256_GCM,data:pA8prvgg0ba2jhOnsPp/AtVL9VSYe5Nqvo7PUZzXPDjYXoP6iz7C2T5DJXCwZB6C09+Iuypw1RV2eCUaSAao3VmK,iv:MubB+fNDkQF1+847TVu14HTR9lyI9uKe1LP78cMz1ME=,tag:QsSOSu3YR+ma13/Z1bmrFQ==,type:comment]
#
#ENC[AES256_GCM,data:aFg5qImx5p1im9YOQ/ZnYFvu8Gf8+xIl/iX+ZU2Ye4kB8zrZtGxSm8JHnph5utAOjjWiLRtWoyy2WxvXJa+ekbAI,iv:9arPFBPGxlX9tv/fgMvLcQnnwHT4VOB6FgCoK9VOqqA=,tag:MGslfF4p0DJFGFgeiT3Rxw==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:xviYOtpiQLWpDk6WCzP5+W6BFg==,iv:frTGjqglA7echc4aYQb7jhVOfQr/bHT7z2tJUXtV/gw=,tag:ELkLi1UAL9e7pqhPyt7Qsw==,type:str]
REDIS_URL: ENC[AES256_GCM,data:oVqi8z8ToeAhc9ekAj6D9lmTa3nOYw==,iv:IAUzWFKV+UapL2rSRo1djhUU1h2xe8tw6iHD1VUj7Wo=,tag:+ZOF0msr2CeGm8qsNHWa9w==,type:str]
JWT_ACCESS_SECRET: ENC[AES256_GCM,data:f2E3ebENX7nT2DLvo9uakDXGTXl5f7plvVw=,iv:miV1w3cdjRSXZDa7l0JLT1YWPEyvAyQIsJgO982xuCg=,tag:p4PzR0fhOTjUhlCeorBGtA==,type:str]
JWT_REFRESH_SECRET: ENC[AES256_GCM,data:p0pBOMV5ikhV04DB9fRJtYBYjll9vo5I/tY=,iv:Gu+5V+2Cbj0m899T4fUPiRYk9pHBSC9SnyudLMOheZo=,tag:3iTf1GmvrFo+3HChle7JHA==,type:str]
JWT_ANON_SECRET: ENC[AES256_GCM,data:BWbhg08qGTkSPYuj3TYOLscgamp3HwxRjUo=,iv:qKhjUe7ZQHfP/aIsV6PgGyYVWYJYpwsugxxsH7DjqzA=,tag:Qd2v+Rs2qJlwAskhZQ7RqA==,type:str]
JWT_ACCESS_EXPIRES_IN: ENC[AES256_GCM,data:e04=,iv:LS+E4dVzZEMJXrzJg5q+O7QWXl6eq4XjCU6bXo3K6g0=,tag:bBGUOba6zSPGKHJx6H/24w==,type:str]
JWT_REFRESH_EXPIRES_IN: ENC[AES256_GCM,data:7l+J,iv:8WjZ0gu27ifpDomzmnKQddk3IrcZqoukbDwAfbANoMc=,tag:CxNppURn6+vFsrBZ30UWSw==,type:str]
FINGERPRINT_SALT: ENC[AES256_GCM,data:9YeHd3PIvFowK3ubN0w3tns=,iv:2ddTaEi7eapWr6S5dYBCr9TvXDetimkVOTznNzb+BvQ=,tag:dASsS1kBJGGBM6X4npAeSg==,type:str]
INVITE_CODE: ENC[AES256_GCM,data:lwMUrKy3xic3RHhaK+ynOMEbaSMBRQ==,iv:eQ61OQH76dtK5S5GfzrKjFvZZBtjrbWX/8qapi7gowI=,tag:lJVhkERx9/+Oe6EFEC8+Zw==,type:str]
CORS_ORIGIN: ENC[AES256_GCM,data:RuP7YHFrfSksAEfnJElB22LHiiM8n2vuFY0ZmsGQqOYZ,iv:deHiy07FjedWUe3Sn/8b45ntp/o8fuswnHE/2kqgF8g=,tag:DaOwM9kiJQ9PwCytr0LNoQ==,type:str]
ROOM_CAPACITY_LIMIT: ENC[AES256_GCM,data:lCbd,iv:PYPqI1NWWBOeO07ofGcXB7rJr2OUq9HOP+cnfuiqjYg=,tag:2FeM/Gp3uokUWp8Qcu3UzA==,type:str]
IMAGE_TAG: ENC[AES256_GCM,data:xDpnUX7S,iv:4XYcoJVjr7SX8WejH2HrK4wBmmx3CK/l3kv2d/2OVR8=,tag:CwVyZL6caeuNmR7o2FimMQ==,type:str]
GH_OWNER: ENC[AES256_GCM,data:Ud2Do3fd/ts0rb4=,iv:RWYPu9yrBIFveSKvsBSC9jKJ4f7pZJM1XS44UprWdCU=,tag:MvCfzjiJnz0y1E6EtDSWlA==,type:str]
DOMAIN: ENC[AES256_GCM,data:RQqPhDHFBchHgBqJ1fApcTC0xT1xyfhv6g==,iv:O7zmc6UHH/ZQfC2M6w8xXE0gH0+LSCwfoIGxuSRgp2I=,tag:QE0IDLE8C/Q2+bRGKUEAcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aWdDbGJYUjlJMUN4M0Fw
            ZVlEMWRIR2Nwc3FBeDVCQkI1cjAzWElOcWc4CkFubTBvVFdVb2FSN1BITjZraC9q
            N05XMFdCb1h0M0NNOVVqWnR6aGF6MG8KLS0tIDJoQXdaQlpvSDVDcE01TDArMW1o
            YWFKcjVGdG9qNGJUbkNTWndMSkI2Z0EKT7lHXRd2uA3b60DFgAuA7iRSYkaJe4Xo
            /m6q/9DM8JD5QwtaDhBKKyzg4IWNQsjAPXicy5ubKNT0Ke37ccRXAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kjspspx3q6saucd6y69yezh0hkjq5rzvfthe227zp5gpvprrlvnqdan684
    lastmodified: "2026-05-10T21:10:52Z"
    mac: ENC[AES256_GCM,data:utMm81g3Bf6wDfSFzP3yKTJIkY6T2TNPXzQXIuHDvANbHoDayN005WE0lZv3FcPSWvKGYKRvDrwq4cDUnUVkVTO1E+l35n6gF/27cjwNHldxEaTdlwJWqpiTVW2VDPEbgSEypD/4z+TerWbUewpZAUPWRT9xXqVprQV0IycHclM=,iv:5HPjND+53i25dhZxlNKNf2qgBKNgffFCyADMvVhkiLM=,tag:z61BTA+sXa9R6wklGV5LEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
